export const employees = [
  {
    id: 1,
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    department: "Engineering",
    position: "Senior Developer",
    salary: 95000,
    hireDate: "2020-01-15",
    age: 32,
    location: "New York",
    performanceRating: 4.2,
    projectsCompleted: 12,
    isActive: true,
    skills: ["JavaScript", "React", "Node.js"],
    manager: "Sarah Johnson",
  },
  {
    id: 2,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@email.com",
    department: "Marketing",
    position: "Marketing Manager",
    salary: 78000,
    hireDate: "2019-03-20",
    age: 35,
    location: "Los Angeles",
    performanceRating: 4.5,
    projectsCompleted: 8,
    isActive: true,
    skills: ["Digital Marketing", "SEO", "Analytics"],
    manager: "Michael Brown",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@email.com",
    department: "Marketing",
    position: "VP Marketing",
    salary: 125000,
    hireDate: "2017-06-10",
    age: 42,
    location: "Los Angeles",
    performanceRating: 4.7,
    projectsCompleted: 15,
    isActive: true,
    skills: ["Strategy", "Leadership", "Brand Management"],
    manager: "",
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@email.com",
    department: "Engineering",
    position: "Engineering Manager",
    salary: 115000,
    hireDate: "2018-02-12",
    age: 38,
    location: "New York",
    performanceRating: 4.6,
    projectsCompleted: 18,
    isActive: true,
    skills: ["Team Leadership", "Architecture", "Python"],
    manager: "David Wilson",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@email.com",
    department: "Engineering",
    position: "CTO",
    salary: 180000,
    hireDate: "2015-08-01",
    age: 48,
    location: "New York",
    performanceRating: 4.8,
    projectsCompleted: 25,
    isActive: true,
    skills: ["Technical Strategy", "Leadership", "Cloud Architecture"],
    manager: "",
  },
  {
    id: 6,
    firstName: "Lisa",
    lastName: "Garcia",
    email: "lisa.garcia@email.com",
    department: "Sales",
    position: "Sales Representative",
    salary: 65000,
    hireDate: "2021-04-15",
    age: 29,
    location: "Chicago",
    performanceRating: 3.9,
    projectsCompleted: 6,
    isActive: true,
    skills: ["CRM", "Negotiation", "Customer Relations"],
    manager: "Robert Martinez",
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Martinez",
    email: "robert.martinez@email.com",
    department: "Sales",
    position: "Sales Manager",
    salary: 92000,
    hireDate: "2018-09-10",
    age: 37,
    location: "Chicago",
    performanceRating: 4.3,
    projectsCompleted: 11,
    isActive: true,
    skills: ["Sales Strategy", "Team Management", "B2B Sales"],
    manager: "Jennifer Lee",
  },
  {
    id: 8,
    firstName: "Jennifer",
    lastName: "Lee",
    email: "jennifer.lee@email.com",
    department: "Sales",
    position: "VP Sales",
    salary: 135000,
    hireDate: "2016-05-20",
    age: 44,
    location: "Chicago",
    performanceRating: 4.6,
    projectsCompleted: 16,
    isActive: true,
    skills: ["Strategic Sales", "Leadership", "Market Analysis"],
    manager: "",
  },
  {
    id: 9,
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@email.com",
    department: "HR",
    position: "HR Specialist",
    salary: 58000,
    hireDate: "2020-11-05",
    age: 31,
    location: "Austin",
    performanceRating: 4.0,
    projectsCompleted: 7,
    isActive: true,
    skills: ["Recruitment", "Employee Relations", "HRIS"],
    manager: "Karen White",
  },
  {
    id: 10,
    firstName: "Karen",
    lastName: "White",
    email: "karen.white@email.com",
    department: "HR",
    position: "HR Manager",
    salary: 85000,
    hireDate: "2017-10-12",
    age: 39,
    location: "Austin",
    performanceRating: 4.4,
    projectsCompleted: 13,
    isActive: true,
    skills: ["HR Strategy", "Policy Development", "Leadership"],
    manager: "",
  },
  {
    id: 11,
    firstName: "Alex",
    lastName: "Thompson",
    email: "alex.thompson@email.com",
    department: "Engineering",
    position: "Junior Developer",
    salary: 72000,
    hireDate: "2022-01-10",
    age: 25,
    location: "New York",
    performanceRating: 3.8,
    projectsCompleted: 4,
    isActive: true,
    skills: ["Java", "Spring Boot", "MySQL"],
    manager: "Sarah Johnson",
  },
  {
    id: 12,
    firstName: "Maria",
    lastName: "Rodriguez",
    email: "maria.rodriguez@email.com",
    department: "Finance",
    position: "Financial Analyst",
    salary: 68000,
    hireDate: "2020-07-15",
    age: 30,
    location: "Miami",
    performanceRating: 4.1,
    projectsCompleted: 9,
    isActive: true,
    skills: ["Financial Modeling", "Excel", "SAP"],
    manager: "Thomas Clark",
  },
  {
    id: 13,
    firstName: "Thomas",
    lastName: "Clark",
    email: "thomas.clark@email.com",
    department: "Finance",
    position: "Finance Manager",
    salary: 98000,
    hireDate: "2018-04-20",
    age: 41,
    location: "Miami",
    performanceRating: 4.5,
    projectsCompleted: 14,
    isActive: true,
    skills: ["Financial Planning", "Budget Management", "Leadership"],
    manager: "",
  },
  {
    id: 14,
    firstName: "Amanda",
    lastName: "Taylor",
    email: "amanda.taylor@email.com",
    department: "Marketing",
    position: "Content Specialist",
    salary: 55000,
    hireDate: "2021-08-10",
    age: 27,
    location: "Los Angeles",
    performanceRating: 3.7,
    projectsCompleted: 5,
    isActive: true,
    skills: ["Content Writing", "Social Media", "Adobe Creative"],
    manager: "Michael Brown",
  },
  {
    id: 15,
    firstName: "Ryan",
    lastName: "Miller",
    email: "ryan.miller@email.com",
    department: "Engineering",
    position: "DevOps Engineer",
    salary: 88000,
    hireDate: "2019-11-15",
    age: 34,
    location: "Seattle",
    performanceRating: 4.3,
    projectsCompleted: 10,
    isActive: true,
    skills: ["AWS", "Docker", "Kubernetes"],
    manager: "Sarah Johnson",
  },
  {
    id: 16,
    firstName: "Jessica",
    lastName: "Moore",
    email: "jessica.moore@email.com",
    department: "Sales",
    position: "Account Executive",
    salary: 75000,
    hireDate: "2020-03-10",
    age: 32,
    location: "Denver",
    performanceRating: 4.0,
    projectsCompleted: 8,
    isActive: false,
    skills: ["Account Management", "Salesforce", "Presentation"],
    manager: "Robert Martinez",
  },
  {
    id: 17,
    firstName: "Daniel",
    lastName: "Harris",
    email: "daniel.harris@email.com",
    department: "Finance",
    position: "Senior Accountant",
    salary: 73000,
    hireDate: "2019-05-15",
    age: 36,
    location: "Miami",
    performanceRating: 4.2,
    projectsCompleted: 12,
    isActive: true,
    skills: ["Accounting", "Tax Preparation", "QuickBooks"],
    manager: "Thomas Clark",
  },
  {
    id: 18,
    firstName: "Nicole",
    lastName: "Jackson",
    email: "nicole.jackson@email.com",
    department: "HR",
    position: "Recruiter",
    salary: 62000,
    hireDate: "2021-02-20",
    age: 28,
    location: "Austin",
    performanceRating: 3.9,
    projectsCompleted: 6,
    isActive: true,
    skills: ["Talent Acquisition", "LinkedIn Recruiter", "Interviewing"],
    manager: "Karen White",
  },
  {
    id: 19,
    firstName: "Kevin",
    lastName: "Wright",
    email: "kevin.wright@email.com",
    department: "Engineering",
    position: "QA Engineer",
    salary: 76000,
    hireDate: "2020-09-01",
    age: 33,
    location: "Seattle",
    performanceRating: 4.1,
    projectsCompleted: 11,
    isActive: true,
    skills: ["Test Automation", "Selenium", "API Testing"],
    manager: "Sarah Johnson",
  },
  {
    id: 20,
    firstName: "Stephanie",
    lastName: "Lopez",
    email: "stephanie.lopez@email.com",
    department: "Marketing",
    position: "Digital Marketing Specialist",
    salary: 64000,
    hireDate: "2022-03-15",
    age: 26,
    location: "Phoenix",
    performanceRating: 3.8,
    projectsCompleted: 7,
    isActive: true,
    skills: ["Google Ads", "Facebook Ads", "Email Marketing"],
    manager: "Michael Brown",
  },
];